name: Update README with latest repositories

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest repositories
        run: |
          curl -s "https://api.github.com/users/johnnywoode/repos?sort=created&per_page=5" | 
          jq -r '.[] | "- [\(.name)](\(.html_url))"' > latest-repos.md

      - name: Update README.md
        run: |
          sed -i '/<!-- BLOG-POST-LIST:START -->/,/<!-- BLOG-POST-LIST:END -->/c\<!-- BLOG-POST-LIST:START -->\n'$(cat latest-repos.md)'\n<!-- BLOG-POST-LIST:END -->' README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated latest repositories"
          git push
